=== enricorotundo/unioverflow/db/db.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <!-- DB -->

    <xs:element name="db" type="Tdb" /> <!-- Unico elemento globale -->
    
    <xs:complexType name="Tdb">
        <xs:sequence> 

            <xs:element name="users" type="Tusers">
                <xs:unique name="uniqueEmail" >
                    <xs:selector xpath="db/users/user" />
                    <xs:field xpath="email" />
                </xs:unique>
            </xs:element>

            <xs:element name="questions" type="Tquestions" > 
                <xs:unique name="uniqueQuestion" >
                    <xs:selector xpath="db/questions/question" />
                    <xs:field xpath="@id" />
                </xs:unique>
            </xs:element>

            <xs:element name="answers" type="Tanswers" >
                <xs:unique name="uniqueAnswer" >
                    <xs:selector xpath="db/answers/answer" />
                    <xs:field xpath="@id" />
                </xs:unique>
            </xs:element>

        </xs:sequence>
    </xs:complexType>

    <!-- USERS -->

    <xs:complexType name="Tusers">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="user" type="Tuser" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tuser">
        <xs:sequence>
            <xs:element name="email" type="Temail" />
            <xs:element name="password" type="Tpassword" />
        </xs:sequence>
    </xs:complexType> 

     <!-- QUESTIONS -->
        
    <xs:complexType name="Tquestions">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="question" type="Tquestion"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tquestion">
        <xs:sequence>
            <xs:element name="title" type="Ttitle" />
            <xs:element name="content" type="Tcontent" />
            <xs:element name="author" type="Temail" />
            <xs:element name="insertDate" type="xs:date" />
            <xs:element name="status" type="Tstatus"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <!-- ANSWERS -->

    <xs:complexType name="Tanswers">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="answer" type="Tanswer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tanswer">
        <xs:sequence>
            <xs:element name="content" type="Tcontent" />
            <xs:element name="author" type="Temail" />
            <xs:element name="question" type="xs:unsignedInt" />
            <xs:element name="insertDate" type="xs:date" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <!-- TYPES -->

    <xs:simpleType name="Temail"> 
        <xs:restriction base="xs:string"> 
            <xs:pattern value="[a-z.]{1,64}@studenti.unipd.it"/> 
        </xs:restriction> 
    </xs:simpleType>

    <xs:simpleType name="Tcontent"> 
        <xs:restriction base="xs:string"> 
            <xs:pattern value=".+"/>  <!-- TODO: completare regex -->
        </xs:restriction> 
    </xs:simpleType>

    <xs:simpleType name="Ttitle"> 
        <xs:restriction base="xs:string"> 
            <xs:pattern value=".{1,300}"/>  <!-- TODO: completare regex -->
        </xs:restriction> 
    </xs:simpleType>

    <xs:simpleType name="Tpassword"> 
        <xs:restriction base="xs:string">
          <xs:pattern value="[a-zA-Z0-9]{8,24}"/> <!-- TODO: da confermare -->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Tstatus">
      <xs:restriction base="xs:string">
        <xs:enumeration value="opened"/>
        <xs:enumeration value="solved"/>
      </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== enricorotundo/unioverflow/db/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<db xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.unioverflow.com db.xsd">
	<users>
		<user>
			<email>enrico.rotundo@studenti.unipd.it</email>
			<password>12345678</password>
		</user>
		<user>
			<email>mario.rossi@studenti.unipd.it</email>
			<password>ciaociao</password>
		</user>
		<user>
			<email>mar.rossi@studenti.unipd.it</email>
			<password>provaprovaprova</password>
		</user>
		<user>
			<email>prova@studenti.unipd.it</email>
			<password>utente3738AkkkaA</password>
		</user>
	</users>
	<questions>
		<question id="0">
			<title>Title1</title>
			<content>Contenuto domanda 1 **grassetto** *italico* </content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<insertDate>2014-01-01</insertDate>
			<status>opened</status>
		</question>
		<question id="1">
			<title>Title2</title>
			<content>Contenuto domanda 2</content>
			<author>mar.rossi@studenti.unipd.it</author>
			<insertDate>2014-01-02</insertDate>
			<status>solved</status>
		</question>
		<question id="3">
			<title>Title3</title>
			<content>Contenuto domanda 3</content>
			<author>prova@studenti.unipd.it</author>
			<insertDate>2014-01-03</insertDate>
			<status>opened</status>
		</question>
		<question id="4">
			<title>Title4</title>
			<content>Contenuto domanda 4</content>
			<author>mar.rossi@studenti.unipd.it</author>
			<insertDate>2014-01-04</insertDate>
			<status>opened</status>
		</question>
		<question id="5">
			<title>Title5</title>
			<content>Contenuto domanda 5</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<insertDate>2014-01-11</insertDate>
			<status>solved</status>
		</question>
		<question id="6">
			<title>Title6</title>
			<content>Contenuto domanda 6</content>
			<author>prova@studenti.unipd.it</author>
			<insertDate>2014-01-10</insertDate>
			<status>solved</status>
		</question>
		<question id="7">
			<title>Title7</title>
			<content>Contenuto domanda 7</content>
			<author>prova@studenti.unipd.it</author>
			<insertDate>2014-01-19</insertDate>
			<status>solved</status>
		</question>
		<question id="8"><title>erthgdth</title><author>enrico.rotundo@studenti.unipd.it</author><content> thrrthr</content><insertDate>2014-4-21</insertDate><status>opened</status></question><question id="9"><title>sdfsdf</title><author>enrico.rotundo@studenti.unipd.it</author><content> sdfsdfsdf</content><insertDate>2014-4-21</insertDate><status>opened</status></question><question id="10"><title>esdfgrt</title><author>enrico.rotundo@studenti.unipd.it</author><content> hfthdthrt</content><insertDate>2014-4-21</insertDate><status>opened</status></question><question id="11"><title>rthrth</title><author>enrico.rotundo@studenti.unipd.it</author><content> rthtrhhtrhrtgfbbfdbdfg</content><insertDate>2014-4-21</insertDate><status>opened</status></question><question id="12"><title>fgbgfbfglktyujhrew</title><author>enrico.rotundo@studenti.unipd.it</author><content> ejtyfcsdvdsfre&amp;lt;</content><insertDate>2014-4-21</insertDate><status>opened</status></question><question id="13"><title>tydjsjhrth</title><author>enrico.rotundo@studenti.unipd.it</author><content> jrhdrthrth</content><insertDate>2014-4-21</insertDate><status>opened</status></question>
	<question id="14"><title>ghmgh</title><author>enrico.rotundo@studenti.unipd.it</author><content>ghmghmgh</content><insertDate>2014-4-21</insertDate><status>opened</status></question><question id="15"><title>Voluptate voluptas praesentium proident est mollit</title><author>enrico.rotundo@studenti.unipd.it</author><content>Qui duis alias eaque fugiat, laboris non optio, tenetur perspiciatis, alias fugiat, corporis ut amet, sapiente.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="16"><title>Aut ea aliquid odio odio tempore vitae quod corporis est commodi deserunt quaerat est mollitia deserunt cupiditate repellendus Inventore</title><author>enrico.rotundo@studenti.unipd.it</author><content>Amet, aliqua. Qui sequi culpa, id rerum quia molestias accusantium ea eos quidem iste ad exercitation rerum.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="17"><title>Ipsa tempora officia illo proident sit mollitia</title><author>enrico.rotundo@studenti.unipd.it</author><content>Harum do quos qui repudiandae repudiandae ut quisquam et fugiat, minus ratione omnis velit molestiae culpa.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="18"><title>Non autem cupidatat omnis ut mollit quae</title><author>enrico.rotundo@studenti.unipd.it</author><content>Officia architecto tempora in quae ut sint magni duis ut velit consequatur, sapiente quasi aut in voluptatum.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="19"><title>Qui et molestiae obcaecati nostrud repellendus Consectetur sint dolor nisi eveniet quas et sequi voluptas pariatur</title><author>enrico.rotundo@studenti.unipd.it</author><content>Laborum qui omnis excepteur temporibus ut culpa natus qui voluptatem.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="20"><title>Ipsa quam quia omnis exercitationem odio nemo veniam molestiae dolor dolores voluptatem Est distinctio A ut</title><author>enrico.rotundo@studenti.unipd.it</author><content>Dignissimos tenetur mollitia ullam ex id quam eius eu laboris quam adipisicing sed ipsa, odit est in voluptate et.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="21"><title>Ipsa eiusmod eum modi ullam commodo minima perspiciatis dolore nostrum nihil aut ad aut</title><author>enrico.rotundo@studenti.unipd.it</author><content>Asperiores consequatur quod commodo doloribus ipsam minus sit, voluptate culpa, delectus, nulla dolore ut ipsum, molestiae.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="22"><title>Et quis fugiat eveniet error sint aut</title><author>enrico.rotundo@studenti.unipd.it</author><content>Aut nulla obcaecati numquam id, eum consequatur hic in consequatur eius nulla quam reiciendis fuga. Autem ullam animi.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="23"><title>Et quis fugiat eveniet error sint aut</title><author>enrico.rotundo@studenti.unipd.it</author><content>Aut nulla obcaecati numquam id, eum consequatur hic in consequatur eius nulla quam reiciendis fuga. Autem ullam animi.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="24"><title>Deserunt quis iure placeat ea ut nihil</title><author>enrico.rotundo@studenti.unipd.it</author><content>Ipsa, quibusdam non sunt sint cumque amet, non facilis nobis a distinctio. Lorem consectetur modi.</content><insertDate>2014-4-22</insertDate><status>opened</status></question><question id="25"><title>Quisquam adipisicing pariatur Magni quo excepturi est</title><author>enrico.rotundo@studenti.unipd.it</author><content>Odio ex dolore explicabo. Quidem et eiusmod corporis debitis minim quidem anim totam laborum. Voluptatem.</content><insertDate>2014-4-22</insertDate><status>opened</status></question></questions>
	<answers>
		<answer id="0">
			<content>Prima risposta **grassetto** *italico*</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-11-23</insertDate>
		</answer>
		<answer id="1">
			<content>Seconda risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>1</question>
			<insertDate>2014-12-24</insertDate>
		</answer>
		<answer id="2">
			<content>Terza risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-11-23</insertDate>
		</answer>
		<answer id="3">
			<content>Quarta risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-12-24</insertDate>
		</answer>
		<answer id="4">
			<content>Quinta risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-11-23</insertDate>
		</answer>
		<answer id="5">
			<content>Sesta risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-12-24</insertDate>
		</answer>
		<answer id="6">
			<content>Settima risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-11-23</insertDate>
		</answer>
		<answer id="7">
			<content>Ottava risposta</content>
			<author>enrico.rotundo@studenti.unipd.it</author>
			<question>0</question>
			<insertDate>2014-12-24</insertDate>
		</answer>
	</answers>
</db>
