=== enricorotundo/unioverflow/db/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.unioverflow.com" xmlns="http://www.unioverflow.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element maxOccurs="unbounded" name="user" type="Tuser"/>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    <xs:complexType name="Tuser">
    	<xs:sequence>
    		<xs:element name="email" type="xs:string" />
    		<xs:element name="password" type="xs:string" />
    	</xs:sequence>
    </xs:complexType>
</xs:schema>

=== enricorotundo/unioverflow/db/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet type="text/xsl" href="users.xsl"?> -->
<users xmlns="http://www.unioverflow.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.unioverflow.com users.xsd">
	<user>
		<email>enrico.rotundo@gmail.com</email>
		<password>admin</password>
	</user>
	<user>
		<email>utente1@gmail.com</email>
		<password>utente1</password>
	</user>
	<user>
		<email>utente2@gmail.com</email>
		<password>utente2</password>
	</user>
	<user>
		<email>utente3@gmail.com</email>
		<password>utente3</password>
	</user>
</users>

=== enricorotundo/unioverflow/db/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.unioverflow.com users.xsd">
	<user>
		<email>enrico.rotundo@studenti.unipd.it</email>
		<password>12345678</password>
	</user>
	<user>
		<email>mario.rossi@studenti.unipd.it</email>
		<password>ciaociao</password>
	</user>
	<user>
		<email>mar.rossi@studenti.unipd.it</email>
		<password>provaprovaprova</password>
	</user>
	<user>
		<email>prova@studenti.unipd.it</email>
		<password>utente3738AkkkaA</password>
	</user>
<user><email>email</email><password>pass</password></user></users>
